"""Create platform table

Revision ID: 4dcaf57052a7
Revises: 998c4e3ad7ee
Create Date: 2026-05-04 15:06:11.675450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4dcaf57052a7'
down_revision: Union[str, Sequence[str], None] = '998c4e3ad7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_api_key'), 'platform', ['api_key'], unique=True)
    op.create_index(op.f('ix_platform_name'), 'platform', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_name'), table_name='platform')
    op.drop_index(op.f('ix_platform_api_key'), table_name='platform')
    op.drop_table('platform')
    # ### end Alembic commands ###
